/**:
  ros__parameters:
    # node_name: "picam_ros2"
    topic_prefix: '/picam_ros2/camera_'
    log_message_every_sec: 5.0
    log_scroll: False

    calibration_frames_needed: 10
    calibration_square_size_m: 0.0175 # set this to your actual calibration square dimension!
    calibration_pattern_size: [ 9, 6 ] # set this to your calibration chessboard size!
    calibration_files: '/calibration' # calibration files saved here

    /camera_80000: # 0 is the camera location
      frame_id: 'Left_Cam_frame'

      enabled: True
      enable_calibration: True
      width: 1920
      height: 1080
      hflip: False
      vflip: False

      hw_encoder: True # True=using hw-encoder, False=CPU
      bitrate: 3000000
      compression: 100 # 0=no compression, 100=max
      framerate: 30

      publish_h264: False
      publish_info: True
      publish_image: True
      image_output_format: bgr8 # output format for the image topic (yuv420, mono8 or bgr8)
      
      ae_enable: True # auto exposure enabled
      # exposure_time_ns: 30000 # manually set fixed exposure time if ae_enable=False
      awb_enable: True # auto white-balance 
      # awb_mode: 0 # 0=auto, 1=incandescent, 2=tungsten, 3=fluorescent, 4=indoor, 5=daylight, 6=cloudy
      contrast: 1.3
      analog_gain: 1.0 # analog gain of the sensor

      # buffer_count: 4 # number of capture buffers

    /camera_88000: # 0 is the camera location
      frame_id: 'Right_Cam_frame'

      enabled: True
      enable_calibration: True
      width: 1920
      height: 1080
      hflip: False
      vflip: False

      hw_encoder: True # True=using hw-encoder, False=CPU
      bitrate: 3000000
      compression: 100 # 0=no compression, 100=max
      framerate: 30

      publish_h264: False
      publish_info: True
      publish_image: True
      image_output_format: bgr8 # output format for the image topic (yuv420, mono8 or bgr8)
      
      ae_enable: True # auto exposure enabled
      # exposure_time_ns: 30000 # manually set fixed exposure time if ae_enable=False
      awb_enable: True # auto white-balance 
      # awb_mode: 0 # 0=auto, 1=incandescent, 2=tungsten, 3=fluorescent, 4=indoor, 5=daylight, 6=cloudy
      contrast: 1.3
      analog_gain: 1.0 # analog gain of the sensor

      # buffer_count: 4 # number of capture buffers
