<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="distance_to_roller_center" value="0.04509"/>
    
    <!-- roller creation -->
    <xacro:macro name="insert_roller" params="parent reflect theta suffix wheel">
        <joint name="rim_to_roller${wheel}${suffix}joint" type="continuous">
            <origin xyz="${distance_to_roller_center*cos(theta)} ${distance_to_roller_center*sin(theta)} ${reflect*0.008 + 0.045}" rpy="0.0 0.0 ${theta-PI/2}"/>
            <parent link="${parent}"/>
            <child link="roller${wheel}${suffix}_link"/>
            <axis xyz="1.0 0.0 0.0"/>
            <dynamics friction="0.1"/>
        </joint>

        <link name="roller${wheel}${suffix}_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find sAMR_description)/meshes/roller.stl" scale= "0.001 0.001 0.001"/>
                </geometry>
                <material name="${material}"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find sAMR_description)/meshes/roller.stl" scale= "0.001 0.001 0.001"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.003"/>
                <inertia ixx="5.3e-8"
                         ixy="0.0"
                         ixz="0.0"
                         iyy="8e-8"
                         iyz="0.0"
                         izz="8e-8"/>
            </inertial>
        </link>
        <gazebo reference="roller${wheel}${suffix}_link">
            <material>Gazebo/Black</material>
            <fdir1>1 0 0"</fdir1>
            <mu1>100</mu1>
            <mu2>100</mu2>
            <minDepth>0.001</minDepth>
        </gazebo>

    </xacro:macro>

    <!-- Macro to define a wheel -->
    <xacro:macro name="wheel_macro" params="suffix theta chassis_radius material">
        <!-- Joint for the wheel -->
        <joint name="wheel${suffix}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="wheel${suffix}_link"/>
            <origin xyz="${chassis_radius*cos(theta)} ${chassis_radius*sin(theta)} -0.09953" 
                    rpy="0.0 -2.35619 ${theta+PI}"/>
            <axis xyz="0.0 0.0 1.0"/>
        </joint>

        <!-- Link for the wheel -->
        <link name="wheel${suffix}_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find sAMR_description)/meshes/wheel.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="${material}"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find sAMR_description)/meshes/wheel.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>

            <!-- Optional: Inertial properties -->
            <inertial>
                <origin xyz="0 0 0"/>
                <mass value="0.0285"/> <!-- Adjust based on your design -->
                <inertia ixx="1.1e-05" ixy="0" ixz="0"
                         iyy="1.1e-05" iyz="0"
                         izz="2.1e-05"/>
            </inertial>
        </link>
        
        <!-- First-layer(from shaft) -->
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="0" suffix="1" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="${2*PI/9}" suffix="2" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="${4*PI/9}" suffix="3" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="${6*PI/9}" suffix="4" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="${8*PI/9}" suffix="5" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="${10*PI/9}" suffix="6" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="${12*PI/9}" suffix="7" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="${14*PI/9}" suffix="8" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="1.1" theta="${16*PI/9}" suffix="9" wheel="${suffix}"/>

        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${PI/9}" suffix="-1" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${PI/3}" suffix="-2" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${5*PI/9}" suffix="-3" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${7*PI/9}" suffix="-4" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${9*PI/9}" suffix="-5" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${11*PI/9}" suffix="-6" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${13*PI/9}" suffix="-7" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${15*PI/9}" suffix="-8" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel${suffix}_link" reflect="-1.1" theta="${17*PI/9}" suffix="-9" wheel="${suffix}"/>

    </xacro:macro>

</robot>
